#!/bin/bash

# Update the system packages
sudo apt update

# Install HAProxy
sudo apt-get install -y haproxy

# Enable HAProxy service
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Configure HAProxy
cat <<EOT | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    user haproxy
    group haproxy
    maxconn 4096

defaults
    log global
    mode http
    option httplog
    option dontlognull
    retries 3
    option redispatch
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http-in
    bind *:80
    default_backend imrane.tech

backend imrane.tech
    balance roundrobin
    server 385397-web-01 54.205.197.191:80 check
    server 385397-web-02 54.237.111.59:80 check
EOT

# Restart HAProxy using systemctl
sudo systemctl restart haproxy

